FROM golang:1.24 AS build

WORKDIR /app

COPY test-service-go/ .

RUN go mod download
RUN go build -o test-service-go .

FROM ghcr.io/netcracker/qubership/core-base:1.0.0 AS run

COPY --chown=10001:0 --chmod=555 --from=build app/test-service-go /app/mesh-test-service-go
COPY --chown=10001:0 --chmod=444 --from=build app/application.yaml /app/

WORKDIR /app

USER 10001:10001

CMD ["/app/mesh-test-service-go"]